### PR TITLE
Add migrations docs

### PR DESCRIPTION
**Pull request by coco98**

### CODE REVIEW

**Comment by coco98** [comment]
@shahidhk @arvi3411301 You guys need to fill in some docs. I've added todos. Grep for Shahidh or Arvi to see which sections.

Needs https://github.com/hasura/graphql-engine/issues/122

**Comment by shahidhk** [comment]
@coco98 Done

**Comment by shahidhk** [comment]
@coco98 @rikinsk Can we merge and deploy this?

**Comment by shahidhk** [comment]
merged directly on master

**Pull request closed without merging**
